### ISSUE TITLE
Repositories/Accession Info?

### ISSUE THREAD

**Issue by ColauttiLab** [LymeMIND/LM2-study-supporting-materials#1]
Congrats on a very impressive study! I have a student interested to learn RNA-Seq analysis by analyzing published datasets and we noticed in your paper this statement:

The datasets presented in this study can be found in online repositories. The names of the repository/repositories and accession number(s) can be found below: https://github.com/LymeMIND/LM2-study-supporting-materials/tree/main/data.

However, we are having trouble finding the repository and accession numbers here. Many thanks if you could clarify this.

**Comment by u8sand** [comment]
@ColauttiLab this *is* the repository for the anonymized/deidentified LymeMIND data, it's not currently on GEO.

The external COVID-19 infection dataset we used to contrast against our patients is mentioned in the jupyter notebook, it is: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152418

There is also a repository of datasets throughout the whole consortium that may have data that you're looking for: https://commons.lymemind.org/

I hope this clarifies things, please let us know if you have any further questions.
